# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: Ftuuky's blog
description: experimental ‚ù§
github_username: ftuuky

# Email and twitter are optional:
email: 
twitter_username: 

# Everything below here can be ignored, unless you want to change the theme entirely
theme: minima
plugins:
  - jekyll-feed

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

